export const USER_GET_ALL = 'USER_GET_ALL'
export const USER_GET_ALL_SUCCESS = 'USER_GET_ALL_SUCCESS'

export const USER_DELETE = 'USER_DELETE'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE'

export const USER_CREATE = 'USER_CREATE'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE'
export const USER_AUTHENTICATE = 'USER_AUTHENTICATE'
export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS'
export const USER_AUTHENTICATE_FAILURE = 'USER_AUTHENTICATE_FAILURE'
export const USER_LOGOUT = 'USER_LOGOUT'

export const QUESTION_GET_ALL = 'QUESTION_GET_ALL'
export const QUESTION_GET_ALL_SUCCESS = 'QUESTION_GET_ALL_SUCCESS'

export const ANSWER_QUESTION = 'ANSWER_QUESTION'
export const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS'
